apiVersion: v1
kind: Service
metadata:
  name: dtq-grafana
  labels:
    app: dtq-grafana
spec:
  selector:
    app: dtq-grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
